#!/bin/bash
#OAR -l /nodes=1, walltime=00:29:00
#OAR -t devel
# test ci-dessous ne marche pas
##OAR -l {"cpumodel='Gold 5218'"}/nodes=1, walltime=00:29:00
##OAR -l {"cpumodel='Gold 6130'"}/nodes=1, walltime=00:29:00
#OAR -t heterogeneous
#OAR --project pr-snowmeca

# pour compiler amitex sur gridcad
#    source /applis/site/nix.sh
#    nix-env -i -A nur.repos.gricad.intel-oneapi
#    source  ~/.nix-profile/setvars.sh
#    modif du install pour compilation avec ifort et mkl
#
# pour lancer amitex
#   oarsub -S ./script_tests_gricad


# compilateur utilisé
FC=ifort

if [[ $FC = "ifort" ]]
then

  source /applis/site/nix.sh
  source ~/.nix-profile/setvars.sh

fi

  cd /home/vedrinel-ext/LG/amitex_fftp/validation


 ./script_tests.sh
